postgres:
    image: postgres
    ports:
        - '5432:5432'
    environment:
        POSTGRES_USER: 'user'
        POSTGRES_PASSWORD: 'password'
        POSTGRES_DB: 'accounts'
    volumes:
        - ./init.sql:/docker-entrypoint-initdb.d/init.sql

