
CREATE SCHEMA FISH_FEEDER;

CREATE TABLE USERS (
	ID INT GENERATED ALWAYS AS IDENTITY,
	NAME varchar(255) NOT NULL,
	EMAIL varchar(255) NOT NULL,
	TANK_ID numeric NULL,
	ADMIN boolean NOT NULL DEFAULT FALSE,
	CONSTRAINT EMAIL_UNIQUE UNIQUE (EMAIL)
);

CREATE TABLE TANKS (
	ID INT GENERATED ALWAYS AS IDENTITY,
	NAME varchar(255) NOT NULL,
	FEED_INTERVAL numeric NOT NULL
);

CREATE TABLE FISH (
	ID INT GENERATED ALWAYS AS IDENTITY,
	NAME varchar(35) NOT NULL,
	TANK_ID numeric NOT NULL,
	DOB date NOT NULL
);

CREATE TABLE HISTORY (
	ID INT GENERATED ALWAYS AS IDENTITY,
	TANK_ID numeric NOT NULL,
	USER_ID numeric NOT NULL,
	FEED_TIME date NOT NULL
);

INSERT INTO TANKS (NAME, FEED_INTERVAL) VALUES('tnk3', 24);

INSERT INTO USERS (NAME, EMAIL, TANK_ID, ADMIN) VALUES('PADDY', 'paddyclaffey@gmail.com', 1, true);

INSERT INTO FISH (NAME, TANK_ID, DOB) VALUES('Steve', 1, '2017-04-15');
INSERT INTO FISH (NAME, TANK_ID, DOB) VALUES('Liam', 1, '2017-04-15');

